### ISSUE TITLE
Call Issues appears white page

### ISSUE THREAD

**Issue by namyslok** [aprey10/open-poker#34] opened 2022-08-12 08:43 UTC
Hi,

issues are not displayed. Blank pages is displayed. It is called with Jira Software 8.22.2/9.1, Firefox 91.6.0esr/Chrome 104.0.5112.81.
We analyzed the error together with Atlassian and found that the Open Poker plugin is causing the error. As soon as Open Poker is deactivated, the display works again.

With best regards
MaNa

**Comment by aprey10** [comment] 2022-09-26 03:19
Hello,
sorry for the long response - I somehow missed this issue.

Hm... that's weird.
Do you use Jira Server or Data Center?
Did it work before or it was always like that?
Have you checked jira logs?

**Comment by namyslok** [comment] 2022-10-24 08:25
Hi,

we use Jira DataCenter. The plugin worked before upgrading to Jira 9. There is nothing usable in the log files.

**Comment by Sandman0724JFW** [comment] 2022-12-29 20:46
We too are experiencing this exact problem and we work around it by disabling the Open-Poker plugin. We're running Jira server 9.1.
Atlassian support noticed the below associated error from our developer console output in Google chrome. 

TypeError: $ is not a function
    at opSyncInit (batch.js?agile_global_admin_condition=true&baseurl-check-resources=true&healthcheck-resources=true&jag=true&jaguser=true&jira.create.linked.issue=true&locale=en-US&richediton=true:920:292)
    at HTMLDocument.<anonymous> (batch.js?agile_global_admin_condition=true&baseurl-check-resources=true&healthcheck-resources=true&jag=true&jaguser=true&jira.create.linked.issue=true&locale=en-US&richediton=true:920:43)
    at i (batch.js?locale=en-US:169:22867)
    at Object.add [as done] (batch.js?locale=en-US:169:23187)
    at E.fn.ready (batch.js?locale=en-US:169:25242)
    at batch.js?agile_global_admin_condition=true&baseurl-check-resources=true&healthcheck-resources=true&jag=true&jaguser=true&jira.create.linked.issue=true&locale=en-US&richediton=true:920:26
    at batch.js?agile_global_admin_condition=true&baseurl-check-resources=true&healthcheck-resources=true&jag=true&jaguser=true&jira.create.linked.issue=true&locale=en-US&richediton=true:920:193
WRMCB @ batch.js?agile_global_admin_condition=true&baseurl-check-resources=true&healthcheck-resources=true&jag=true&jaguser=true&jira.create.linked.issue=true&locale=en-US&richediton=true:1
2?jql=:88

**Comment by aprey10** [comment] 2023-01-02 03:55
@Sandman0724JFW 
I managed to reproduce the error that you posted and started investigating it. I'm planning to release the new version with the fix. I'll keep you posted.

**Comment by aprey10** [comment] 2023-01-02 05:31
@Sandman0724JFW , @namyslok 
Hope you had a good New Year and Christmas,

I identified what caused that javascript issue and published a new version of the plugin (2.3.0) with the fix.
I have tested it locally and I don't see that error in Chrome Console anymore. I'm still not sure if that issue could cause a "blank page" since locally I can't reproduce it. Please try to upgrade the plugin to the latest version and let me know if there is any issue.

Also, I have noticed that my test env has some implicit caching and because of that it used an incorrect jira version under the hood and that's why I haven't seen this JS problem before. Now, I fixed that too - so my local testing should be more accurate.

Regards,
Andriy

**Comment by Sandman0724JFW** [comment] 2023-01-04 19:34
Hi Andriy,

We’ve updated Open-Poker in our Jira environments and it does look to have resolved the issue for us. Thanks so much for your prompt response. Our development team is happy.

Thanks,
Jeff

**Comment by aprey10** [comment] 2023-01-06 20:41
I'm glad it works! :)

closing the issue

**Closed by aprey10** 2023-01-06 20:41 UTC
